### ISSUE TITLE
css编写及命名规范

### ISSUE THREAD

**Issue by lounj** [77ircloud/FET#18]
css规范文章
针对ircloud-ydh-web项目的css规范
### 1. 文件位置和命名
css文件放在当前组件根目录文件夹下,采用**驼峰式命名**，和js命名保持一致
```js
    -product
	-detail
    	    -productDetail.scss
            -index.js
```
### 2. css文件内部编写规则
一个css文件对应一个页面，最好使用最外层类包含所有，对于有的不能包含的弹窗样式就放在根类外面。
```css
.product-detail {
    .product-detail-header {
        font-size: 12px;
        ...
    }
    .product-detail-body {
        width: 100%;
        ...
    }
}
```
#### 3.1. 不要使用ID选择器
```css
//bad
#id {
    width: 100%;
}
//good
.class {
    width: 100%;
}
```
#### 3.2. 在一个规则声明中应用了多个选择器时，每个选择器独占一行
```css
//bad
.selector1, selector2 {
    width: 100%;
}
//good
.selector1,
.selector2 {
    width: 100%;
}
```
### 4. class命名规范
BEM命名法：block-element-modifier
例：
```css
.user-home-nav
    .user-home-nav-item
    .user-home-nav-item-icon
    .user-home-nav-item-text
```
在scss中
```scss
.user-home-nav {
    &-item {
        &-icon {}
        &-text {}
    }
}
```
BEM使代码重用性降低，但利于维护，便于维护带来的好处绝对超过代码冗余带来的坏处。
BEM命名范例：
```js
    <div class="product-detail">
    	    <div class="product-detail-header">
                //此TXT和body中txt可共用
               <div class="product-detail-txt"></div>
                //当名称过长的时候也最好确保是BEM格式
                <div class="detail-header-status"></div>
                //带有modifier的class
               <div class="detail-header-status--success"></div>
               <div class="detail-header-status--error"></div>
            </div>
            <div class="product-detail-body">
                 //此TXT和body中txt可共用
                <div class="product-detail-txt"></div>
                 //当名称过长的时候也最好确保是BEM格式 (BEM格式并不是要求只有一个B一个E)
                <div class="detail-body-status"></div>
                //带有modifier的class
                <div class="detail-body-status--active"></div>
                <div class="detail-body-status--noactive"></div>
           </div>
    </div>
```
此上代码片段作为规范参考。
有相关想法的可以和我沟通，相互学习。
